Fix TestDelayedPebbleReady pebble-ready issues with ops 2.0.0rc2
Previously these tests had the following error when trying to use
ops 2.0.0rc2:

Traceback (most recent call last):
  File "/home/ben/w/loki-k8s-operator/tests/unit/test_charm.py", line 377, in setUp
    self.harness.begin_with_initial_hooks()
  File "/home/ben/w/loki-k8s-operator/.tox/unit/lib/python3.10/site-packages/ops/testing.py", line 353, in begin_with_initial_hooks
    self.container_pebble_ready(container_name)
  ...
NotImplementedError: <bound method _TestingPebbleClient.exec of <ops.testing._TestingPebbleClient object at 0x7f562f1207c0>>

It was happening because of the changes to begin_with_initial_hooks()
now triggering pebble-ready. Use begin() instead here, and manually
emit config-changed so the charm status is set to WaitingStatus.

Also remove the warning about the unexpected asyncio_mode config key
in pyproject.toml's pytest configuration.